<a href="https://colab.research.google.com/github/Wendyshiro/ReIntroduction-to-Machine-Learning/blob/main/Copy_of_Intro_to_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Welcome to the CSV Files
In this lesson we'll learn the basics of data preprocessing for machine learning using Python and the Pandas library.

## Introducing Pandas

Pandas, short for 'panel data', makes data manipulation easy. With Pandas, a dataset can be converted into a Python object known as a **DataFrame**, which comes with a variety of handy methods.

In [ ]:
import pandas as pd

# in vanilla Python, a DataFrame's structure is roughly analogous to the following:
dataframe_struct = {"Celestial Object": ["Mars", "Saturn", "Pluto (RIP)", "Mercury", "Europa", "Titan"],
                    "Miles away (in M)": [208, 1008, 3292, 64, 1100, 1212],
                    "Inhabited by aliens?": [True, False, False, True, True, True]}
# convert dataframe_struct into a DataFrame
df = pd.DataFrame(dataframe_struct)
# print the DataFrame's first five rows
df.head()

  Celestial Object  Miles away (in M)  Inhabited by aliens?
0             Mars                208                  True
1           Saturn               1008                 False
2      Pluto (RIP)               3292                 False
3          Mercury                 64                  True
4           Europa               1100                  True

## Mount Google Drive for Data Import

The code block below will connect this Colab notebook to your Google Drive account. From there, we'll be able to load the dataset you've downloaded to your Google Drive into this notebook.


Run the code block and it'll ask you to authenticate via Google. Click yes through everything.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Reading Data From External Files

With the basics out of the way, let's pull in the UFO data.

Assuming your dataset is downloaded to the root of your Google Drive, the path passed to `pd.read_csv()` below should work just fine.

In [ ]:
ufo_data = pd.read_csv('/content/drive/My Drive/ufo_data.csv')
ufo_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999 entries, 0 to 1998
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   summary         1994 non-null   object
 1   city            1986 non-null   object
 2   state           1910 non-null   object
 3   date_time       1945 non-null   object
 4   shape           1839 non-null   object
 5   duration        1813 non-null   object
 6   stats           1999 non-null   object
 7   report_link     1999 non-null   object
 8   text            1994 non-null   object
 9   posted          1945 non-null   object
 10  city_latitude   1654 non-null   float64
 11  city_longitude  1654 non-null   float64
dtypes: float64(2), object(10)
memory usage: 187.5+ KB

In [ ]:
ufo_data = pd.read_csv('/content/drive/My Drive/ufo-data1.zip')

## An Optional Note On Slice Notation
If you've never seen colons used to splice ranges of data before in Python, some of the syntax that follows can be a little confusing.

In brief, the slice operator `:` works by extracting a subset of a list where the left-hand term is inclusive and the right-hand term is exclusive. So, if we wanted to slice a `ufo_list` into a smaller subset, we'd use `ufo_list[this_is_included:and_this_is_not].` We can also step backward from the end of the list with the `-` negative operator.

Learn more about ranges and slicing in the [Python docs](https://docs.python.org/3/tutorial/introduction.html#text) (you'll need to scroll down a little.)

In [ ]:
# for instance, consider this list
list = ['a','b','c','d','e','f']
print(list[1:3]) # remember the list is zero indexed!
print(list[:4]) # the value after the colon indicates where the new sequence should end..
print(list[2:]) # .. while the first indicates where it should start.
print(list[:]) # if both terms are missing, *all* items are returned
print(list[-4:-1]) # from the Python docs: "Note that since -0 is the same as 0, negative indices start from -1." it's still exclusive, so 'f' is left out.
print(list[::-1]) # the optional third parameter indicates a 'step', so the code on this line reverses the element in its entirety

['b', 'c']
['a', 'b', 'c', 'd']
['c', 'd', 'e', 'f']
['a', 'b', 'c', 'd', 'e', 'f']
['c', 'd', 'e']
['f', 'e', 'd', 'c', 'b', 'a']

## Locating and Selecting Data with `loc` and `iloc`

### `loc` and labels

`loc` locates data via its label. By default, rows are usually not labeled, so our first examples will only select columns.

In [ ]:
summaries = ufo_data.loc[:, "summary"]
summaries.head()

0                                       freaked me out
1    One object observed at closer ground distance,...
2    UFO contact we made during Desert Shield in th...
3    Over a course of 5 years, I have seen UFOs, ob...
4    Driving north on US 87 just outside Brady, Tex...
Name: summary, dtype: object

In [ ]:
label_list = ufo_data.loc[:, ["summary","shape","duration"]]
label_list.head()

,summary,shape,duration
0,freaked me out,sphere,2 minutes
1,"One object observed at closer ground distance,...",unknown,2400 hours
2,UFO contact we made during Desert Shield in th...,NaN,NaN
3,"Over a course of 5 years, I have seen UFOs, ob...",formation,Years
4,"Driving north on US 87 just outside Brady, Tex...",light,Lights disappear

In [ ]:
label_range = ufo_data.loc[:, "city":"shape"]
label_range.head()

         city state            date_time      shape
0    San Jose    CA  2021-05-06T21:00:00     sphere
1    Somerset    KY                  NaN    unknown
2         NaN   NaN                  NaN        NaN
3  Germantown    MD  2005-07-06T12:00:00  formation
4       Brady    TX  2020-01-29T19:45:00      light

#### An aside on index columns

In [ ]:
# after setting the index column, `loc` will access each row via that column's value
col_indexed_data = ufo_data.set_index("shape", inplace=False, drop=True)
# now we can select rows using their labels with loc.
#fill in the code below to select all rows with the label 'fireball'
row_select = col_indexed_data.loc["fireball", :]
print(row_select)

# now try printing summaries of all rows labeled "sphere"
col_indexed_data.loc["sphere", "summary"]

                                                    summary  \
shape
fireball                              meteor or space junk?
fireball     Fireball in southeast sky that changed shapes.
fireball  So me and my brother were driving home through...
fireball  Went outside to take a smoke looked up saw abo...
fireball              30+ orange balls playing in Australia
fireball  2 shimmering fireballs hovering in the sky bef...
fireball  Shooting star/fireball bright green light fall...
fireball  shootingstar/fireball bright green light falli...
fireball  The Ohio, Winsor, ONT & Pennsylvania Aug 25th ...
fireball                                       Cube of Fire
fireball           Light green meteor sighting near Airport
fireball  While seated looking east from a 10th floor I ...
fireball                                 Orb like fireballs
fireball  It was 10:00 at night and I Was walking to my ...
fireball  It look like it was a shooting star but it was...
fireball  Flaming object cross an open area between two ...
fireball  Fast moving ball of light was moving up and down.
fireball  Fireball or (meteor?) Might be something stran...
fireball  It began around 10pm, it was myself and severa...
fireball  I was driving with a nine-year-old over Chenie...
fireball  Bright, glowing red light transitions from hov...
fireball  The realization of the anomolie & the eeery si...
fireball  From right to left. Imagine a large aircraft a...
fireball  Large Fireballs appeared orniting each other b...
fireball  I have video of two beings coming up from unde...
fireball  Around 8:20pm Central standard time i witnesse...
fireball  Near military airbase, high in sky, object exp...
fireball   A green fireball moving across the sky at night.
fireball  moving north to south slowly, orange glowing b...
fireball  moving north to south slowly, orange glowing b...
fireball  A very bright green object streaked over me in...
fireball  Introduction: On 04/21/2020 at approximately 0...
fireball  Six friends see a strange fireball flying in a...
fireball  I went out to my car from from work for a quic...
fireball  Flaming ball of light making right angle turns...
fireball  Red fireball type object seen at height of low...
fireball  bal of fire in the sky no reported air crashes...
fireball                         Fireball and  missing time
fireball  A fireball fly bye and may be blow but it disa...
fireball                         ball of fire in summer sky
fireball  various coloured fireball emitting sparks and ...
fireball            huge orange circular fireball in Quebec
fireball  Me and my fiance witnessed 3 lights move in od...
fireball  What is the bright orange object, in Houston’s...
fireball  White object seen by driver in northern Virgin...
fireball  one fireball in the sky then 3 black shapes co...
fireball      Two tailed burning object moving erratically.
fireball  Several craft was shooting into the air and it...
fireball           Orange Pulsating Orbs in Huntersville NC
fireball  Flaming object traveling extremely quickly fro...
fireball  Sometime in March, 1995, at 0630, facing west,...
fireball  a ball of light, that fell from the sky, sudde...
fireball  I was driving on 590 going towards 6. I look u...
fireball                              hovering ball of fire
fireball  Sighting of strange orange light (ball of fire...
fireball  Green Fireball Sighted Near Albuquerque Moving...
fireball                     Fireball seen above Brandon sd
fireball  Bright, orange/reddish light spotted moving ov...
fireball  Coming from South towards San Diego. There was...
fireball  Bright green fireball in SE sky while heading ...

                                 city state            date_time  \
shape
fireball                    San Diego    CA  2020-01-29T20:10:00
fireball                 Mastic Beach    NY  2020-01-12T18:57:00
fireball                        Wayne    NY  2020-01-05T08:00:00
fireball                         Clay    AL  2005-07-11T01:30:00
fireball           Hobart (Australia)   NaN  1982-03-16T18:00:00
fireball                   Unionville    MI  1993-10-29T20:00:00
fireball                      Reading    PA  1994-05-11T05:16:00
fireball                      Reading    PA  1994-05-11T05:16:00
fireball                       Oregon    OH  1995-08-25T01:10:00
fireball  Stoke on Trent (UK/England)   NaN  1999-04-04T22:00:00
fireball                   Moses Lake    WA  2017-10-12T13:24:00
fireball              Fort Lauderdale    FL  2020-04-07T18:45:00
fireball                    Las Vegas    NV  2020-04-12T20:13:00
fireball                       Bandon    OR  2020-04-12T23:00:00
fireball              Kolkata (India)   NaN                  NaN
fireball                 Severna Park    MD  1993-06-01T14:00:00
fireball                     Franklin    WI  2020-04-15T19:45:00
fireball                 Cedar Rapids    IA  2009-10-08T23:00:00
fireball                      Swansea    SC  2010-11-10T23:00:00
fireball                  West Monroe    LA  2012-07-06T00:00:00
fireball                Hannawa Falls    NY  2012-08-12T01:00:00
fireball                   Shell Lake    WI  2017-10-01T22:00:00
fireball         Riviera Mya (Mexico)   NaN  2017-10-19T20:10:00
fireball                  Mount Holly    NC  2020-04-17T20:00:00
fireball                   Gig Harbor    WA  2019-07-07T23:00:00
fireball                Grand Prairie    TX  2020-04-17T20:20:00
fireball                       Warren    OH  2019-08-26T12:56:00
fireball                   Chesapeake    VA  2019-09-12T20:30:00
fireball                    Watertown    NY  2019-10-01T23:00:00
fireball                    Watertown    NY  2019-10-04T23:00:00
fireball                     Bluffton    SC  2019-10-05T06:30:00
fireball                     Seabrook    TX  2020-04-21T02:45:00
fireball                     Newberry    MI  2020-04-21T03:00:00
fireball                       Yakima    WA  2019-10-06T05:15:00
fireball                 Independence    MO                  NaN
fireball                       Sequim    WA  2019-10-08T23:45:00
fireball                   El Cerrito    CA                  NaN
fireball                     Vineland    NJ                  NaN
fireball                      Inkster    MI  2019-10-09T07:05:00
fireball                     Stockton    CA  1970-07-22T20:00:00
fireball                      Toronto    ON  1971-07-15T11:00:00
fireball                Les Escoumins    QC  1972-07-01T18:00:00
fireball                       Coburg    ON  2019-10-09T22:00:00
fireball                      Houston    TX  2019-10-10T19:00:00
fireball                     Culpeper    VA  2019-10-11T19:30:00
fireball                      Phoenix    AZ  1986-07-13T18:00:00
fireball                      Elkwood    VA  2019-10-11T20:05:00
fireball                   Statesboro    GA  2020-04-28T09:30:00
fireball                 Huntersville    NC  2019-10-12T21:30:00
fireball                      Medford    OR  2020-04-28T20:45:00
fireball                  San Antonio    TX  1995-03-15T06:30:00
fireball                         Sage    CA  1995-05-15T04:30:00
fireball                       Hawley    PA  2019-10-13T22:15:00
fireball                      Alabama    AL  1996-06-18T17:30:00
fireball   Poole, Dorset (UK/England)   NaN  1998-01-08T22:00:00
fireball                  Albuquerque    NM  1998-07-15T01:30:00
fireball                      Brandon    SD  2019-10-16T06:30:00
fireball                  Los Angeles    CA  2020-04-29T21:25:00
fireball                       Perris    CA  2019-10-17T20:15:00
fireball                    Jefferson    GA  2019-10-17T23:11:00

                     duration  \
shape
fireball            2 seconds
fireball            4 minutes
fireball           30 minutes
fireball          1-2 minutes
fireball            5 minutes
fireball           15 minutes
fireball  A couple of seconds
fireball  A couple of seconds
fireball            5 minutes
fireball            4 minutes
fireball            3 seconds
fireball           10 seconds
fireball            2 minutes
fireball            2 minutes
fireball           10 minutes
fireball            9 seconds
fireball             1 minute
fireball            4 seconds
fireball      3 hours or more
fireball            <1 minute
fireball            3 minutes
fireball            5 minutes
fireball             1 minute
fireball             1 minute
fireball           16 seconds
fireball           15 seconds
fireball            2 minutes
fireball                  30s
fireball            3 minutes
fireball            3 minutes
fireball            2 seconds
fireball           15 minutes
fireball            4 minutes
fireball            3 minutes
fireball         several hrs.
fireball            2 minutes
fireball            2 minutes
fireball        10 to 20 sec.
fireball                00:05
fireball            5 seconds
fireball            3 seconds
fireball        a few minutes
fireball           50 minutes
fireball            3 minutes
fireball            2 minutes
fireball               20mins
fireball            5 minutes
fireball               5 mins
fireball             5 minute
fireball           10 seconds
fireball           10 seconds
fireball                  NaN
fireball            5 seconds
fireball                 3min
fireball          10 seconds?
fireball          1-2 minutes
fireball                2 min
fireball        10-15 seconds
fireball            5 minutes
fireball           30 seconds

                                                      stats  \
shape
fireball  Occurred : 1/29/2020 20:10  (Entered as : 1/29...
fireball  Occurred : 1/12/2020 18:57  (Entered as : 01/1...
fireball  Occurred : 1/5/2020 08:00  (Entered as : 01/05...
fireball  Occurred : 6/30/2019 01:30  (Entered as : 2019...
fireball  Occurred : 3/16/1982 18:00  (Entered as : 03/1...
fireball  Occurred : 10/29/1993 20:00  (Entered as : 10/...
fireball  Occurred : 5/11/1994 05:16  (Entered as : 05/1...
fireball  Occurred : 5/11/1994 05:16  (Entered as : 05/1...
fireball  Occurred : 8/25/1995 01:10  (Entered as : 08/2...
fireball  Occurred : 4/4/1999 22:00  (Entered as : 04/04...
fireball  Occurred : 10/12/2017 13:24  (Entered as : 043...
fireball  Occurred : 4/7/2020 18:45  (Entered as : 04/07...
fireball  Occurred : 4/12/2020 20:13  (Entered as : 04/1...
fireball  Occurred : 4/12/2020 23:00  (Entered as : 04/1...
fireball  Occurred :  20:08  (Entered as : 20:08) Report...
fireball  Occurred : 6/1/1993 14:00  (Entered as : 06/01...
fireball  Occurred : 4/15/2020 19:45  (Entered as : 4/15...
fireball  Occurred : 10/8/2009 23:00  (Entered as : 10/0...
fireball  Occurred : 11/10/2010 23:00  (Entered as : 11/...
fireball  Occurred : 7/6/2012   (Entered as : 07/06/12) ...
fireball  Occurred : 8/12/2012 01:00  (Entered as : 08/1...
fireball  Occurred : 10/1/2017 22:00  (Entered as : 10/2...
fireball  Occurred : 10/19/2017 20:10  (Entered as : 17/...
fireball  Occurred : 4/17/2020 20:00  (Entered as : 04/1...
fireball  Occurred : 7/7/2019 23:00  (Entered as : July ...
fireball  Occurred : 4/17/2020 20:20  (Entered as : 04/1...
fireball  Occurred : 8/26/2019 12:56  (Entered as : 08/2...
fireball  Occurred : 9/12/2019 20:30  (Entered as : 09/1...
fireball  Occurred : 10/1/2019 23:00  (Entered as : 10/0...
fireball  Occurred : 10/4/2019 23:00  (Entered as : 10/0...
fireball  Occurred : 10/5/2019 06:30  (Entered as : 10/0...
fireball  Occurred : 4/21/2020 02:45  (Entered as : 04/2...
fireball  Occurred : 4/21/2020 03:00  (Entered as : 4/21...
fireball  Occurred : 10/6/2019 05:15  (Entered as : 10/0...
fireball  Occurred : 8/8/1955 01:00  (Entered as : 08/08...
fireball  Occurred : 10/8/2019 23:45  (Entered as : 10/0...
fireball  Occurred : 1/10/1964 20:00  (Entered as : 01-1...
fireball  Occurred : 8/10/1968 19:00  (Entered as : 8/10...
fireball  Occurred : 10/9/2019 07:05  (Entered as : 10/9...
fireball  Occurred : 7/22/1970 20:00  (Entered as : 07/2...
fireball  Occurred : 7/15/1971 11:00  (Entered as : 07/1...
fireball  Occurred : 7/1/1972 18:00  (Entered as : 19720...
fireball  Occurred : 10/9/2019 22:00  (Entered as : 10/9...
fireball  Occurred : 10/10/2019 19:00  (Entered as : 10/...
fireball  Occurred : 10/11/2019 19:30  (Entered as : 10/...
fireball  Occurred : 7/13/1986 18:00  (Entered as : 0316...
fireball  Occurred : 10/11/2019 20:05  (Entered as : 10/...
fireball  Occurred : 4/28/2020 09:30  (Entered as : 04/2...
fireball  Occurred : 10/12/2019 21:30  (Entered as : 10/...
fireball  Occurred : 4/28/2020 20:45  (Entered as : 4/28...
fireball  Occurred : 3/15/1995 06:30  (Entered as : 03/1...
fireball  Occurred : 5/15/1995 04:30  (Entered as : 05/1...
fireball  Occurred : 10/13/2019 22:15  (Entered as : 10/...
fireball  Occurred : 6/18/1996 17:30  (Entered as : 06/1...
fireball  Occurred : 1/8/1998 22:00  (Entered as : 1/8/9...
fireball  Occurred : 7/15/1998 01:30  (Entered as : 7/21...
fireball  Occurred : 10/16/2019 06:30  (Entered as : 10/...
fireball  Occurred : 4/29/2020 21:25  (Entered as : 04/2...
fireball  Occurred : 10/17/2019 20:15  (Entered as : 10/...
fireball  Occurred : 10/17/2019 23:11  (Entered as : 10/...

                                                report_link  \
shape
fireball  http://www.nuforc.org/webreports/152/S152974.html
fireball  http://www.nuforc.org/webreports/152/S152749.html
fireball  http://www.nuforc.org/webreports/152/S152524.html
fireball  http://www.nuforc.org/webreports/153/S153022.html
fireball  http://www.nuforc.org/webreports/155/S155180.html
fireball  http://www.nuforc.org/webreports/155/S155858.html
fireball  http://www.nuforc.org/webreports/156/S156385.html
fireball  http://www.nuforc.org/webreports/156/S156391.html
fireball  http://www.nuforc.org/webreports/156/S156729.html
fireball  http://www.nuforc.org/webreports/155/S155201.html
fireball  http://www.nuforc.org/webreports/156/S156009.html
fireball  http://www.nuforc.org/webreports/155/S155098.html
fireball  http://www.nuforc.org/webreports/155/S155039.html
fireball  http://www.nuforc.org/webreports/155/S155078.html
fireball  http://www.nuforc.org/webreports/149/S149510.html
fireball  http://www.nuforc.org/webreports/149/S149788.html
fireball  http://www.nuforc.org/webreports/155/S155213.html
fireball  http://www.nuforc.org/webreports/149/S149632.html
fireball  http://www.nuforc.org/webreports/150/S150435.html
fireball  http://www.nuforc.org/webreports/150/S150451.html
fireball  http://www.nuforc.org/webreports/150/S150245.html
fireball  http://www.nuforc.org/webreports/149/S149896.html
fireball  http://www.nuforc.org/webreports/149/S149912.html
fireball  http://www.nuforc.org/webreports/155/S155534.html
fireball  http://www.nuforc.org/webreports/150/S150162.html
fireball  http://www.nuforc.org/webreports/155/S155406.html
fireball  http://www.nuforc.org/webreports/150/S150065.html
fireball  http://www.nuforc.org/webreports/150/S150243.html
fireball  http://www.nuforc.org/webreports/149/S149507.html
fireball  http://www.nuforc.org/webreports/149/S149506.html
fireball  http://www.nuforc.org/webreports/149/S149508.html
fireball  http://www.nuforc.org/webreports/155/S155600.html
fireball  http://www.nuforc.org/webreports/155/S155728.html
fireball  http://www.nuforc.org/webreports/150/S150074.html
fireball   http://www.nuforc.org/webreports/050/S50478.html
fireball  http://www.nuforc.org/webreports/149/S149679.html
fireball   http://www.nuforc.org/webreports/050/S50277.html
fireball   http://www.nuforc.org/webreports/049/S49624.html
fireball  http://www.nuforc.org/webreports/149/S149723.html
fireball   http://www.nuforc.org/webreports/049/S49802.html
fireball   http://www.nuforc.org/webreports/050/S50142.html
fireball   http://www.nuforc.org/webreports/049/S49731.html
fireball  http://www.nuforc.org/webreports/149/S149697.html
fireball  http://www.nuforc.org/webreports/149/S149722.html
fireball  http://www.nuforc.org/webreports/149/S149764.html
fireball   http://www.nuforc.org/webreports/049/S49691.html
fireball  http://www.nuforc.org/webreports/149/S149769.html
fireball  http://www.nuforc.org/webreports/155/S155902.html
fireball  http://www.nuforc.org/webreports/149/S149870.html
fireball  http://www.nuforc.org/webreports/155/S155936.html
fireball   http://www.nuforc.org/webreports/049/S49650.html
fireball   http://www.nuforc.org/webreports/050/S50280.html
fireball  http://www.nuforc.org/webreports/149/S149815.html
fireball   http://www.nuforc.org/webreports/050/S50072.html
fireball   http://www.nuforc.org/webreports/050/S50425.html
fireball   http://www.nuforc.org/webreports/050/S50387.html
fireball  http://www.nuforc.org/webreports/150/S150222.html
fireball  http://www.nuforc.org/webreports/155/S155987.html
fireball  http://www.nuforc.org/webreports/150/S150282.html
fireball  http://www.nuforc.org/webreports/151/S151115.html

                                                       text  \
shape
fireball  Meteor or space junk?  There have been several...
fireball  Fireball in southeast sky that changed shapes....
fireball  So me and my brother were driving home through...
fireball  Went outside to take a smoke looked up saw abo...
fireball  30+ orange balls playing in Australia In 1982 ...
fireball  2 shimmering fireballs hovering in the sky bef...
fireball  shootingstar/fireball bright green light falli...
fireball  shootingstar/fireball bright green light falli...
fireball  The Ohio, Winsor, ONT & Pennsylvania Aug 25th ...
fireball  Cube of Fire Object initially seen flying in a...
fireball  Light green meteor sighting near Airport Light...
fireball  While seated looking east from a 10th floor I ...
fireball  Orb like fireballs 3 orb like objects, looked ...
fireball  It was 10:00 at night and I Was walking to my ...
fireball  It look like it was a shooting star but it was...
fireball  Flaming object cross an open area between two ...
fireball  Fast moving ball of light was moving up and do...
fireball  Fireball or (meteor?)  Might be something stra...
fireball  It began around 10pm, it was myself and severa...
fireball  I was driving with a nine-year-old over Chenie...
fireball  Bright, glowing red light transitions from hov...
fireball  The realization of the anomolie & the eeery si...
fireball  From right to left. Imagine a large aircraft a...
fireball  Large Fireballs appeared orniting each other b...
fireball  I have video of two beings coming up from unde...
fireball  Around 8:20pm Central standard time i witnesse...
fireball  Near military airbase, high in sky, object exp...
fireball  A green fireball moving across the sky at nigh...
fireball  moving north to south slowly, orange glowing b...
fireball  moving north to south slowly, orange glowing b...
fireball  A very bright green object streaked over me in...
fireball  Introduction: On 04/21/2020 at approximately 0...
fireball  Six friends see a strange fireball flying in a...
fireball  I went out to my car from from work for a quic...
fireball  Flaming ball of light making right angle turns...
fireball  Red fireball type object seen at height of low...
fireball  bal of fire in the sky no reported air crashes...
fireball  Fireball and  missing time It was a warm augus...
fireball  A fireball fly bye and may be blow but it disa...
fireball  ball of fire in summer sky fireball was 500 fe...
fireball  various coloured fireball emitting sparks and ...
fireball  huge orange circular fireball in Quebec I've s...
fireball  Me and my fiance witnessed 3 lights move in od...
fireball  What is the bright orange object, in Houston’s...
fireball  White object seen by driver in northern Virgin...
fireball  one fireball in the sky then 3 black shapes co...
fireball  Two tailed burning object moving erratically. ...
fireball  Several craft was shooting into the air and it...
fireball  Orange Pulsating Orbs in Huntersville NC I was...
fireball  Flaming object traveling extremely quickly fro...
fireball  Sometime in March, 1995, at 0630, facing west,...

shape
sphere                                       freaked me out
sphere    Reddish orange orbs that changed to white and ...
sphere    Saw several glowing red objects hovering almos...
sphere    High altitude string of spherical objects, tra...
sphere    The object was metallic in color.  Spherical i...
                                ...
sphere    Very bright lights ..sphere shape very large w...
sphere    My girlfriend and I were hammocking in my back...
sphere    My girlfriend and I were hammocking in my back...
sphere    Light spotted over Sweetwater Resivior in Spri...
sphere    UFO seen on KRON 4 News @ 9 during flight dela...
Name: summary, Length: 121, dtype: object

### `iloc` and indexing

In [ ]:
# how would we obtain the first row's fifth column using iloc? (Remember they're both zero indexed.)
ufo_data.iloc[:, :4]

,summary,city,state,date_time
0,freaked me out,San Jose,CA,2021-05-06T21:00:00
1,"One object observed at closer ground distance,...",Somerset,KY,NaN
2,UFO contact we made during Desert Shield in th...,NaN,NaN,NaN
3,"Over a course of 5 years, I have seen UFOs, ob...",Germantown,MD,2005-07-06T12:00:00
4,"Driving north on US 87 just outside Brady, Tex...",Brady,TX,2020-01-29T19:45:00
...,...,...,...,...
1994,Objects look like stars but moving fast in one...,Titusville,FL,2020-04-30T21:05:00
1995,hovering saucer nears ground then disappears i...,Des Moines,IA,2020-04-30T21:09:00
1996,20 plus lights in single file. About 5 minutes...,Saint Augustine,FL,2020-04-30T21:10:00
1997,"A group of spaceships ""danced"" about the sky.","Melbourne (VIC, Australia)",NaN,1996-06-02T13:00:00
1998,Disk object appeared very close to ground abov...,Post,TX,NaN

In [ ]:
# how would you return all rows and only the latitude and longitude columns?
#(they're the last two columns in the DataFrame.)
ufo_data.iloc[:, -2:]

      city_latitude  city_longitude
0         37.338842     -121.889706
1         37.090361      -84.498169
2               NaN             NaN
3         39.154986      -77.272538
4         31.145100      -99.347800
...             ...             ...
1994      28.540221      -80.854386
1995      41.599716      -93.618909
1996      29.879031      -81.366592
1997            NaN             NaN
1998      33.248500     -101.334500

[1999 rows x 2 columns]

In [ ]:
# can you return only the tenth through fifteenth rows and all columns?
ufo_data.iloc[9:15,:]

,summary,city,state,date_time,shape,duration,stats,report_link,text,posted,city_latitude,city_longitude
9,Large Moving Bright Red Light Over Battle Creek,Battle Creek,MI,2020-01-22T19:18:00,light,2 minutes,Occurred : 1/22/2020 19:18 (Entered as : 01/2...,http://www.nuforc.org/webreports/152/S152825.html,Large Moving Bright Red Light Over Battle Cree...,2020-01-31T00:00:00,42.327893,-85.188559
10,Seen 3 middle one flashed as if it were a mirr...,Detroit,MI,2020-01-20T15:00:00,flash,45 minutes,Occurred : 1/20/2020 15:00 (Entered as : 1-20...,http://www.nuforc.org/webreports/152/S152760.html,Seen 3 middle one flashed as if it were a mirr...,2020-01-31T00:00:00,42.368855,-83.110268
11,Fireball in southeast sky that changed shapes.,Mastic Beach,NY,2020-01-12T18:57:00,fireball,4 minutes,Occurred : 1/12/2020 18:57 (Entered as : 01/1...,http://www.nuforc.org/webreports/152/S152749.html,Fireball in southeast sky that changed shapes....,2020-01-31T00:00:00,40.766200,-72.837700
12,A series of soft white lights were traveling i...,Chennai (India),NaN,2020-01-10T05:35:00,light,10-15 minutes,Occurred : 1/10/2020 05:35 (Entered as : 10.0...,http://www.nuforc.org/webreports/152/S152475.html,This early hour of 01.10.2020 a series of soft...,2020-01-31T00:00:00,NaN,NaN
13,I looked up in the sky above the lights and th...,Idaho Falls,ID,2020-01-06T18:45:00,NaN,NaN,Occurred : 1/6/2020 18:45 Reported: 1/6/2020 1...,http://www.nuforc.org/webreports/152/S152332.html,"Jan 6, 2020 At 6:45 I was headed down Broadwa...",2020-01-31T00:00:00,43.473508,-112.003624
14,Bright light going east to west burning steady...,Commercial Point,OH,2020-01-01T20:08:00,NaN,3 seconds,Occurred : 1/1/2020 20:08 (Entered as : 01012...,http://www.nuforc.org/webreports/152/S152148.html,Bright light going east to west burning steady...,2020-01-31T00:00:00,39.769400,-83.064000

## Feature Engineering Our Shape Predictor

A common ML task is combining or otherwise manipulating multiple features into a single feature, part of a process called 'feature engineering.'

Below, observe how we turn the two features 'city' and 'state' into a single feature using basic concatenation.

In [ ]:
ufo_data["city and state"] = ufo_data.loc[:,"city"] + ", " + ufo_data.loc[:,"state"]
ufo_data["city and state"].head()

0      San Jose, CA
1      Somerset, KY
2               NaN
3    Germantown, MD
4         Brady, TX
Name: city and state, dtype: object

## Preparing Data for Machine Learning

In [ ]:
# make a new dataframe called "shape_prediction_data" with three columns in this order:
#  "city and state"
#  "duration"
#  "shape"
shape_prediction_data = ufo_data.loc[:,["city and state", "duration", "shape"]]

shape_prediction_data.head()
shape_prediction_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999 entries, 0 to 1998
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   city and state  1903 non-null   object
 1   duration        1813 non-null   object
 2   shape           1839 non-null   object
dtypes: object(3)
memory usage: 47.0+ KB

Separate our `shape_prediction_data` into features (`city and state` and `duration`) and labels (`shape`) and assign them to `X` and `y` respectively.

In [ ]:
# assuming "shape" is our label and "city and state" and "duration" are our features,
# can you fill in the following two variables?
X = shape_prediction_data.iloc[:,:-1]
y = shape_prediction_data.iloc[:,-1:]

print("feature set:\n", X.head())
print("label:\n", y.head())

feature set:
    city and state          duration
0    San Jose, CA         2 minutes
1    Somerset, KY        2400 hours
2             NaN               NaN
3  Germantown, MD             Years
4       Brady, TX  Lights disappear
label:
        shape
0     sphere
1    unknown
2        NaN
3  formation
4      light